module.exports = {
  USER_CONNECTED: "USER_CONNECTED",
  LOGIN: "LOGIN",
  LOGOUT_USER: "LOGOUT_USER",
  USER_DISCONNECT: "USER_DISCONNECT",
  TYPING: 'TYPING',
  COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
};