module.exports = {
  USER_CONNECTED: "USER_CONNECTED",
  LOGIN: "LOGIN",
  LOGOUT_USER: "LOGOUT_USER",
  USER_DISCONNECT: "USER_DISCONNECT",
  CREATE_CHATS: 'CREATE_CHATS',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
};