export const CONNECTION_PORT = ':8080';

export const USER_CONNECTED = 'USER_CONNECTED';
export const LOGIN = 'LOGIN';
export const MESSAGE_SEND = 'MESSAGE_SEND';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_DISCONNECT = 'USER_DISCONNECT';
export const CREATE_CHATS = 'CREATE_CHATS';
export const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';
